madsim-rs/madsim

- madsim/src/std/net/tcp.rs
> fix(tcp): avoid duplicate connection and close unused connection

- CHANGELOG.md
- README.md
- madsim-macros/Cargo.toml
- madsim-tokio/Cargo.toml
- madsim-tokio/README.md
- madsim-tonic/Cargo.toml
- madsim-tonic/README.md
- madsim/Cargo.toml
> bump version to v0.2.0-alpha.4

- CHANGELOG.md
- README.md
- madsim-macros/Cargo.toml
- madsim-tokio-postgres/Cargo.toml
- madsim-tokio/Cargo.toml
- madsim-tokio/README.md
- madsim-tonic-build/Cargo.toml
- madsim-tonic/Cargo.toml
- madsim-tonic/README.md
- madsim/Cargo.toml
> release: v0.2.0-alpha.5

- CHANGELOG.md
- madsim/src/sim/task.rs
- madsim/src/sim/utils/mpsc.rs
> fix: avoid panic on panicking

- Makefile
- madsim-macros/src/lib.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
> feat: simulate `std::thread::available_parallelism`

- CHANGELOG.md
- Makefile
- README.md
- madsim-macros/Cargo.toml
- madsim-tokio-postgres/Cargo.toml
- madsim-tokio/Cargo.toml
- madsim-tokio/README.md
- madsim-tonic-build/Cargo.toml
- madsim-tonic/Cargo.toml
- madsim-tonic/README.md
- madsim/Cargo.toml
- madsim/src/sim/runtime/mod.rs
> release: v0.2.0-alpha.7

- madsim-tonic/src/transport/channel.rs
required by: https://github.com/singularity-data/risingwave/pull/4505
> feat(tonic): add missing methods to `Endpoint`

- madsim-tonic/Cargo.toml
- madsim-tonic/src/transport/server.rs
> feat(tonic): add missing methods to `Server`

- madsim/Cargo.toml
- madsim/src/sim/fs.rs
- madsim/src/sim/net/endpoint.rs
- madsim/src/sim/net/mod.rs
- madsim/src/sim/net/tcp/listener.rs
- madsim/src/sim/net/tcp/stream.rs
- madsim/src/sim/net/udp.rs
- madsim/src/sim/plugin.rs
- madsim/src/sim/rand.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
- madsim/src/sim/time/mod.rs
- madsim/src/sim/utils/mpsc.rs
> refactor: switch to spin lock

- madsim-tonic/Cargo.toml
- madsim-tonic/src/client.rs
- madsim-tonic/src/codec.rs
- madsim-tonic/src/sim.rs
- madsim-tonic/src/tower.rs
- madsim-tonic/src/transport/mod.rs
- madsim-tonic/src/transport/server.rs
> tonic: reduce dependencies in simulation

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/net/addr.rs
> fix `lookup_host` on 'localhost' and release v0.2.3

- madsim-tonic/src/transport/server.rs
- tonic-example/src/server.rs
Caught by https://github.com/singularity-data/risingwave/issues/4788
> fix(tonic): fix panic when server sends a response but client has closed the stream

- madsim/src/sim/time/system_time.rs
The `minstant` crate uses clockid=6 on Linux virtual machine. 🥵
> fix: support more clockids on linux

- CHANGELOG.md
- madsim-tonic/Cargo.toml
- madsim/Cargo.toml
> release: v0.2.4

- madsim/src/sim/task.rs
> feat: forbid creating system thread in simulation

- tonic-example/src/server.rs
> test(tonic): add test for server crash

- madsim-macros/src/service.rs
- madsim/src/sim/net/endpoint.rs
- madsim/src/sim/net/rpc.rs
- madsim/src/std/net/rpc.rs
- madsim/src/std/net/tcp.rs
- madsim/src/std/net/ucx.rs
> feat(net): make `Endpoint` clonable

- madsim/src/sim/rand.rs
> doc(rand): remove outdated doc

- madsim-etcd-client/src/kv.rs
- madsim-etcd-client/src/server.rs
- madsim-etcd-client/src/service.rs
> feat(etcd): simulate 'etcdserver: request timed out'

- CHANGELOG.md
- README.md
- madsim-etcd-client/Cargo.toml
- madsim-etcd-client/README.md
- madsim-macros/Cargo.toml
- madsim/Cargo.toml
> release: v0.2.5

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim/Cargo.toml
- madsim/src/sim/net/mod.rs
> release: v0.2.6

- Cargo.toml
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/src/client.rs
- madsim-rdkafka/src/config.rs
- madsim-rdkafka/src/consumer.rs
- madsim-rdkafka/src/error.rs
- madsim-rdkafka/src/lib.rs
- madsim-rdkafka/src/message.rs
- madsim-rdkafka/src/metadata.rs
- madsim-rdkafka/src/producer.rs
- madsim-rdkafka/src/topic_partition_list.rs
- madsim-rdkafka/src/types.rs
- madsim-rdkafka/src/util.rs
> feat(kafka): add rdkafka barebone

- CHANGELOG.md
- madsim/Cargo.toml
> release: v0.2.7

- CHANGELOG.md
- madsim-tokio/Cargo.toml
- madsim-tokio/src/lib.rs
- madsim-tokio/src/sim/runtime.rs
> feat(tokio): add fake runtime

- madsim-rdkafka/src/sim/error.rs
- madsim-rdkafka/src/sim/producer.rs
- madsim-rdkafka/tests/test.rs
- madsim/src/sim/net/addr.rs
> feat(kafka): impl transaction for producer

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-rdkafka/Cargo.toml
- madsim/Cargo.toml
> release: v0.2.8

- CHANGELOG.md
- Makefile
- madsim-tokio/Cargo.toml
- madsim-tonic-build/Cargo.toml
- madsim-tonic-build/src/server.rs
- madsim-tonic/Cargo.toml
- madsim/Cargo.toml
- madsim/src/sim/net/endpoint.rs
- madsim/src/sim/net/tcp/mod.rs
> release: v0.2.11

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/task.rs
> fix: panic when await an aborted JoinHandle

- madsim-etcd-client/src/kv.rs
- madsim-etcd-client/src/service.rs
- madsim-etcd-client/tests/test.rs
> feat(etcd): add `create_revision` and `mod_revision` to `KeyValue`

- CHANGELOG.md
- madsim-rdkafka/src/sim/message.rs
- madsim-rdkafka/src/sim/util.rs
> feat(rdkafka): add `Timestamp::to_millis`

- CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/README.md
> release: bump madsim-rdkafka to v0.2.13-alpha

- madsim-etcd-client/src/bytes.rs
- madsim-etcd-client/src/error.rs
- madsim-etcd-client/src/kv.rs
- madsim-macros/src/request.rs
- madsim-rdkafka/src/sim/error.rs
- madsim-rdkafka/tests/test.rs
- madsim-tonic-build/src/client.rs
- madsim/examples/rpc.rs
- madsim/src/sim/fs.rs
- madsim/src/sim/rand.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
- madsim/src/sim/time/interval.rs
- madsim/src/sim/time/system_time.rs
- tonic-example/src/bin/client.rs
- tonic-example/src/lib.rs
> fix clippy in the latest stable toolchain

- CHANGELOG.md
- madsim-etcd-client/tests/test.rs
- madsim-rdkafka/src/sim/admin.rs
- madsim-rdkafka/src/sim/consumer.rs
- madsim-rdkafka/src/sim/producer.rs
- madsim-rdkafka/tests/test.rs
- madsim-tonic/src/transport/channel.rs
- madsim/src/sim/net/addr.rs
- madsim/src/sim/net/dns.rs
- madsim/src/sim/net/mod.rs
- tonic-example/tests/test.rs
> feat: simulate DNS server

- CHANGELOG.md
- madsim-etcd-client/tests/test.rs
- madsim/src/sim/net/ipvs.rs
- madsim/src/sim/net/mod.rs
- madsim/src/sim/net/tcp/mod.rs
> feat: add global IPVS

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-rdkafka/Cargo.toml
- madsim-tonic/Cargo.toml
- madsim/Cargo.toml
> release: v0.2.14

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-etcd-client/examples/test.rs
- madsim-etcd-client/src/service.rs
- madsim-etcd-client/tests/test.rs
> fix(etcd): return error on lease not found

- CHANGELOG.md
- madsim/src/sim/buggify.rs
- madsim/src/sim/mod.rs
- madsim/src/sim/net/mod.rs
- madsim/src/sim/rand.rs
- madsim/src/std/buggify.rs
- madsim/src/std/mod.rs
resolve #80 
When buggify is enabled, all operations will have a long latency at 10% chance.
> feat: introduce buggify

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-tokio/Cargo.toml
- madsim/Cargo.toml
> release: v0.2.15

- CHANGELOG.md
- README.md
- madsim-aws-sdk-s3/Cargo.toml
- madsim-aws-sdk-s3/README.md
> release: madsim-aws-sdk-s3

- CHANGELOG.md
- madsim-aws-sdk-s3/Cargo.toml
- madsim-aws-sdk-s3/src/client/model.rs
- madsim-aws-sdk-s3/src/client/output.rs
- madsim-aws-sdk-s3/src/server/service.rs
- madsim/Cargo.toml
- madsim/src/sim/time/system_time.rs
> fix: fix `clock_gettime` and delete object in s3

- CHANGELOG.md
- madsim-etcd-client/src/service.rs
- madsim-tonic/src/client.rs
- madsim-tonic/src/transport/channel.rs
- tonic-example/proto/helloworld.proto
- tonic-example/src/lib.rs
- tonic-example/tests/test.rs
Also fixed a panic in etcd election.
> feat(tonic): support request timeout

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-tonic/Cargo.toml
- madsim-tonic/src/client.rs
- madsim-tonic/src/codec.rs
- madsim-tonic/src/transport/server.rs
- madsim/Cargo.toml
- tonic-example/tests/test.rs
> fix(tonic): return an error when the server stream is broken

- CHANGELOG.md
- madsim-tonic/Cargo.toml
- madsim-tonic/src/client.rs
- madsim/Cargo.toml
- madsim/src/sim/task/mod.rs
- madsim/src/sim/time/mod.rs
- tonic-example/tests/test.rs
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Unavailable, message: "connection reset", source: None }', /Users/wangrunji/Codes/madsim/madsim-tonic/src/client.rs:164:22
```
> fix(tonic): fix panic on server closed. add `time::advance`

- madsim-tonic/Cargo.toml
A workaround for  https://github.com/chronotope/chrono/issues/602
> fix(tonic): disable chrono default features

- CHANGELOG.md
- madsim-tonic-build/Cargo.toml
- madsim-tonic-build/README.md
- madsim-tonic-build/src/client.rs
- madsim-tonic-build/src/server.rs
- madsim-tonic/Cargo.toml
- madsim-tonic/src/client.rs
- madsim-tonic/src/codec.rs
bump version of madsim-tonic and madsim-tonic-build to v0.3.1
> fix(tonic): add missing APIs

- madsim-tonic/Cargo.toml
- madsim-tonic/src/client.rs
- madsim-tonic/src/transport/channel.rs
- madsim-tonic/src/transport/server.rs
Add support for [`balance_channel`](https://docs.rs/tonic/latest/tonic/transport/struct.Channel.html#method.balance_channel) which could be used to connect multiple endpoints.
> feat(tonic): implement `balance_channel` for `Channel`

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-tonic-build/Cargo.toml
- madsim-tonic/Cargo.toml
- tonic-example/Cargo.toml
https://github.com/hyperium/tonic/blob/master/CHANGELOG.md
> upgrade tonic v0.10.0

- CHANGELOG.md
- README.md
- madsim-etcd-client/Cargo.toml
- madsim-etcd-client/README.md
- madsim-tonic-build/README.md
release madsim-etcd-client v0.4.0+0.12.1
> chore: update etcd-client to v0.12

- CHANGELOG.md
- madsim-tonic-build/Cargo.toml
- madsim-tonic-build/src/server.rs
> fix(tonic-build): fix missing `futures_core` dependency

- CHANGELOG.md
- madsim-tonic-build/Cargo.toml
- madsim-tonic-build/src/prost.rs
resolve #169 
release madsim-tonic-build v0.4.2
> feat(tonic-build): add missing APIs for `Builder`

- CHANGELOG.md
- README.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/README.md
- madsim-rdkafka/src/std/admin.rs
- madsim-rdkafka/src/std/client.rs
- madsim-rdkafka/src/std/config.rs
- madsim-rdkafka/src/std/consumer/base_consumer.rs
- madsim-rdkafka/src/std/consumer/mod.rs
- madsim-rdkafka/src/std/consumer/stream_consumer.rs
- madsim-rdkafka/src/std/error.rs
- madsim-rdkafka/src/std/message.rs
- madsim-rdkafka/src/std/mocking.rs
- madsim-rdkafka/src/std/mod.rs
- madsim-rdkafka/src/std/producer/base_producer.rs
- madsim-rdkafka/src/std/producer/future_producer.rs
- madsim-rdkafka/src/std/producer/mod.rs
- madsim-rdkafka/src/std/statistics.rs
- madsim-rdkafka/src/std/topic_partition_list.rs
- madsim-rdkafka/src/std/util.rs
released as madsim-rdkafka v0.3.0+0.34.0
> chore(rdkafka): bump rdkafka to v0.34.0

- madsim/src/sim/net/addr.rs
> returning an Error instead of panic if parsing socket address fails

- CHANGELOG.md
- madsim-tokio/Cargo.toml
- madsim/Cargo.toml
madsim v0.2.23
madsim-tokio v0.2.24
> chore: release a new version for madsim and madsim-tokio

- madsim-aws-sdk-s3/Cargo.toml
- madsim-aws-sdk-s3/src/client.rs
- madsim-aws-sdk-s3/src/server/service.rs
> chore: bump aws sdk version

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/task/join.rs
resolve #191 . release as madsim v0.2.25
> feat: add `task::AbortHandle::is_finished`

- CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/README.md
> chore: update librdkafka to v2.3.0

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/rand.rs
fix #205. please review @xxchan
> fix: fix unaligned pointer access in getrandom

- .github/workflows/ci.yml
- madsim-etcd-client/src/election.rs
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/README.md
- madsim-rdkafka/src/std/client.rs
- madsim-rdkafka/src/std/producer/future_producer.rs
- madsim-rdkafka/src/std/util.rs
- madsim/src/sim/config.rs
> refactor(rdkafka): make `ENABLE_REFRESH_OAUTH_TOKEN` a function

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/rand.rs
- madsim/src/sim/runtime/builder.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task/mod.rs
> feat(madsim): add an option to allow spawning system thread

- madsim/src/sim/task/mod.rs
> Wait for external events when spawning threads is enabled

- CHANGELOG.md
- madsim-tokio/Cargo.toml
- madsim/Cargo.toml
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task/join.rs
> feat: publish new madsim-tokio
