madsim-rs/madsim

- madsim-sim/src/lib.rs
To match the API exposed by std.
> Add a trivial implementation for `terminate`

- madsim-tonic/src/transport/channel.rs
- madsim-tonic/src/transport/server.rs
- madsim/src/sim/rand.rs
- madsim/src/sim/runtime/mod.rs
`Endpoint::recv` is not cancellation safe! So selecting 2 recv futures may lose message.
> fix(tonic): avoid missing accept on server

- madsim-macros/src/lib.rs
- madsim-tokio/src/lib.rs
- madsim/src/sim/mod.rs
Currently using `#[tokio::main]` still needs an explicit import of the madsim crate. This PR fixes this issue.
> fix(tokio): no longer need to add madsim dependency

- madsim/Cargo.toml
- madsim/src/sim/net/endpoint.rs
- madsim/src/sim/net/mod.rs
- madsim/src/sim/net/network.rs
- madsim/src/sim/net/rpc.rs
- madsim/src/sim/net/tcp/listener.rs
- madsim/src/sim/net/tcp/mod.rs
- madsim/src/sim/net/tcp/stream.rs
- madsim/src/sim/plugin.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
- madsim/src/sim/time/mod.rs
- madsim/src/sim/time/sleep.rs
- madsim/src/sim/utils/mpsc.rs
- tonic-example/src/client.rs
- add `deliver` method to `Socket` trait. let `NetSim` take care of message delivery
- introduce `BindGuard` to auto release a bound port on drop
- introduce channel as a reliable and ordered transport over the network
- refactor TCP implementation using channel
Seems that the new Rust toolchain introduced several clippy rules which generate warnings in `prost` crate. We'll ignore the failure of clippy task.
> refactor(net): introduce channel and refactor TCP

- madsim/src/sim/net/addr.rs
- madsim/src/sim/net/mod.rs
- madsim/src/sim/plugin.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
- madsim/src/sim/time/mod.rs
- deprecate `spawn_blocking`
- panic on DNS lookup
- accept name as the argument of node ctl functions
- rename `TaskNodeHandle` to `Spawner` and deprecate the former
- add tokio unstable `task::Builder` API
> feat(task): add `task::Builder`

- .github/workflows/ci.yml
- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/time/system_time.rs
https://github.com/rust-lang/rust/pull/102368 (nightly-2022-09-29) changed the memory layout of `std::time::{SystemTime, Instant}` on Linux ([code](https://github.com/rust-lang/rust/commit/a91327782906885ccd8b8bf25e1e7f9ea46f8428#diff-3183738c82f747fd92bb573712073aa384b16e14d154bf2df18f41077edc31cbR23)), making them no longer equal to [libc::timespec](https://docs.rs/libc/latest/libc/struct.timespec.html#). So the previous transmute between these types will break data and trigger a panic.
This PR also releases v0.2.9.
> fix(time): fix panic cause by std internal structure change

- CHANGELOG.md
- madsim-rdkafka/src/std/mod.rs
- madsim/Cargo.toml
- madsim/src/sim/runtime/context.rs
This PR fixes the panic on TLS access when getting time at the exit phase.
Also bumps version to 0.2.10.
> fix(runtime): fix panic on TLS access error

- madsim-tokio/src/sim/runtime.rs
- madsim/src/sim/task.rs
... so that the API can be compatible with tokio while not breaking normal builds
> chore(tokio): add new_current_thread with unimplemented

- madsim-etcd-client/Cargo.toml
- madsim-etcd-client/src/bytes.rs
- madsim-etcd-client/src/election.rs
- madsim-etcd-client/src/kv.rs
- madsim-etcd-client/src/server.rs
- madsim-etcd-client/src/service.rs
- madsim-etcd-client/src/sim.rs
- madsim-etcd-client/tests/test.rs
This PR introduces `Client::dump()` and `SimServer::load()` function to dump and load etcd data.
The data would be dumped in pretty json format, in which bytes are encoded in [Rust ascii escape format](https://doc.rust-lang.org/std/ascii/fn.escape_default.html#) to make it human-readable.
Example dump data:
```json
{
"revision": 516,
"kv": {
"cf/meta/leader": "\\n\\x0c0.0.0.0:5690",
},
"lease": {}
}
```
> feat(etcd): support load and dump

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/time/system_time.rs
https://github.com/rust-lang/rust/pull/103594 changed the internal structure of `Instant` on ARM64 macOS.
> fix(time): fix time interception on ARM64 macOS

- CHANGELOG.md
- madsim-etcd-client/Cargo.toml
- madsim-etcd-client/src/kv.rs
- madsim-etcd-client/src/server.rs
- madsim-etcd-client/src/service.rs
- madsim-etcd-client/src/sim.rs
- madsim-etcd-client/src/watch.rs
- madsim-etcd-client/tests/test.rs
- fix response stream of lease `keep_alive`.
- fix waking up other candidates on leadership resign or lease revoke.
- fix unimplemented election `observe`.
- add tests for election API
> fix(etcd): fix various bugs in election API

- CHANGELOG.md
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
To simulate the behavior of process exit.
Also add `Handle::is_exit` API.
> fix(task): kill other tasks after the initial task completes 

- CHANGELOG.md
- madsim/src/sim/task.rs
When killing a node, it may cause a cascade drop for the tasks of this node, where there will be a reentrancy of a lock in the call stack. This way, the program will fall into a deadlock.
This PR fixes it by introducing a temporary store for `runnable` when being wakened up on kill so that the cascade drop can be broken.
> fix: break cascade drop to prevent deadlock on kill

- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/src/std/client.rs
- madsim-rdkafka/src/std/producer/future_producer.rs
Cherry-pick https://github.com/MaterializeInc/rust-rdkafka/commit/8ea07c4d2b96636ff093e670bc921892aee0d56a.
Note that we will no longer publish madsim-rdkafka to crates.io since this PR, because it depends on materialize's fork of rdkafka-sys. But since their patch has been merged into the upstream, we can wait for a new release and then switch it back.
> feat(rdkafka): cherry-pick DNS resolve callback from Materialize

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/net/tcp/mod.rs
- madsim/src/sim/rand.rs
According to the [rand docs](https://docs.rs/rand/latest/rand/rngs/struct.SmallRng.html), `SmallRng` is not considered reproducible across platforms. So replace it with a named PRNG.
> fix: replace RNG for reproducibility

- madsim-etcd-client/src/kv.rs
- madsim-etcd-client/src/server.rs
- madsim-etcd-client/src/service.rs
- madsim-etcd-client/tests/test.rs
This PR fixes the implementation of etcd election API. Currently, there is only one key for each election. But actually each candidate will create a key and the leader is the one with the smallest revision.
Please note that this implementation is still not exactly as the official etcd, where election API is implemented on top of KV and lease API on the client side.
> fix(etcd): fix election implementation

- madsim/src/sim/net/network.rs
- madsim/src/sim/net/tcp/config.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task.rs
example:
```
---- basic stdout ----
thread '<unnamed>' panicked at 'explicit panic', tonic-example/tests/test.rs:43:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
context: node=1 "server", task=33 (spawned at tonic-example/tests/test.rs:42:11)
```
> feat: print context info on panic

- CHANGELOG.md
- madsim-aws-sdk-s3/Cargo.toml
- madsim-aws-sdk-s3/src/server/service.rs
See https://github.com/risingwavelabs/risingwave/issues/10494#issuecomment-1603910637
> fix: fix missing parts ordering in s3 simulator

- CHANGELOG.md
- madsim-aws-sdk-s3/Cargo.toml
- madsim-tonic/Cargo.toml
- madsim-tonic/src/client.rs
- madsim-tonic/src/sim.rs
- tonic-example/tests/test.rs
resolve #155 
Also release v0.2.25 and yank v0.2.24 for madsim-aws-sdk-s3.
> feat(tonic): support setting timeout for each request

- CHANGELOG.md
- README.md
- madsim-etcd-client/Cargo.toml
- madsim-etcd-client/README.md
- madsim-tonic-build/Cargo.toml
- madsim-tonic/Cargo.toml
- madsim-tonic/README.md
- madsim-tonic/src/sim.rs
- madsim-tonic/src/transport/server.rs
... I'm wondering whether we need to bump major version https://github.com/madsim-rs/madsim/issues/145
changelog: https://github.com/hyperium/tonic/blob/master/CHANGELOG.md
I mainly want this: build:: Support boxing fields
> bump tonic version to v0.9

- madsim-tokio/src/sim/runtime.rs
https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.enter
> feat: add tokio::Runtime::enter

- .vscode/settings.json
- madsim-aws-sdk-s3/Cargo.toml
- madsim-aws-sdk-s3/src/client.rs
- madsim-aws-sdk-s3/src/server/service.rs
```
aws-sdk-s3: 0.35 => 0.39
aws-smithy-http: 0.57 => 0.60
aws-smithy-runtime-api: 0.57 => 1.0
aws-smithy-types: 0.57 => 1.0
aws-types: 0.57 => 1.0
```
> chore: bump aws sdk to the latest

- README.md
- madsim-aws-sdk-s3/Cargo.toml
- madsim-aws-sdk-s3/README.md
> chore: bump madsim-aws-sdk-s3 to v0.5.0+1 

- CHANGELOG.md
- madsim-aws-sdk-s3/Cargo.toml
- madsim-rdkafka/Cargo.toml
- madsim/Cargo.toml
- madsim/src/sim/config.rs
- madsim/src/sim/time/system_time.rs
https://github.com/rust-lang/rust/pull/116238 (Rust 1.75) replaced `mach_absolute_time` with `clock_gettime(CLOCK_REALTIME)` on x86_64 macOS.
> fix: fix time on x86_64 macos

- CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/README.md
- madsim-rdkafka/src/std/client.rs
- madsim-rdkafka/src/std/consumer/base_consumer.rs
- madsim-rdkafka/src/std/consumer/mod.rs
- madsim-rdkafka/src/std/consumer/stream_consumer.rs
Please take a look. @BugenZhao @tabVersion
Will release as madsim-rdkafka v0.3.3.
> fix: wrap `fetch_watermarks` in `spawn_blocking`

- CHANGELOG.md
- madsim/Cargo.toml
- madsim/src/sim/time/mod.rs
fix #198 
release madsim v0.2.26
> fix: make `sleep` wait for at least 1ms

- CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/src/std/client.rs
- madsim-rdkafka/src/std/mocking.rs
- madsim-tokio/src/sim/runtime.rs
- madsim/src/sim/rand.rs
- madsim/src/sim/runtime/context.rs
release madsim-rdkafka v0.3.4 and yank v0.3.3
> fix(rdkafka): fix unintended drop of client in `fetch_watermarks`

- CHANGELOG.md
- Cargo.toml
- madsim/Cargo.toml
- madsim/src/sim/rand.rs
This PR fixes #201, a bug happening on Linux only. The reason why `getrandom` yields a different value in the first run is that, a `getrandom(0, 0)` is called on first access to check the availability of this function [(code)](https://github.com/rust-random/getrandom/blob/f68a940b4dac78b49f00599aebd56c72284a92d9/src/linux_android.rs#L12). It mutates the global random state by mistake. This PR adds a branch to avoid the mutation.
release as madsim v0.2.27
> fix(madsim): fix determinism for getrandom

- CHANGELOG.md
- madsim-tokio/Cargo.toml
https://github.com/tokio-rs/tokio/pull/5952
> fix(tokio): remove `stats` feature to allow tokio >=1.33.

- madsim-etcd-client/src/service.rs
- madsim-macros/src/service.rs
- madsim-tokio/src/sim/runtime.rs
- madsim/src/sim/net/endpoint.rs
- madsim/src/sim/net/rpc.rs
- madsim/src/sim/net/tcp/listener.rs
- madsim/src/sim/net/tcp/stream.rs
- madsim/src/sim/net/unix/stream.rs
- madsim/src/sim/runtime/mod.rs
- madsim/src/sim/task/mod.rs
- madsim/src/sim/time/interval.rs
- madsim/src/sim/time/sleep.rs
to support madsim-rs/sqlx, we add some `spawn`, `try_current` and some other dummy interface.
> feat: add spawn and try_current for madsim-tokio

- CHANGELOG.md
- madsim-rdkafka/CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/src/sim/client.rs
- madsim-rdkafka/src/sim/consumer.rs
- madsim-rdkafka/src/sim/producer/future_producer.rs
- madsim-rdkafka/tests/test.rs
> fix(rdkafka): add missing methods in ClientContext.

- madsim-rdkafka/CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/README.md
- madsim-rdkafka/src/std/client.rs
- madsim-rdkafka/src/std/consumer/base_consumer.rs
- madsim-rdkafka/src/std/groups.rs
This PR wraps the following function in `tokio::task::spawn_blocking`:
- Client::fetch_metadata
- Client::fetch_group_list
- Consumer::offsets_for_times
released as v0.4.2
cc @BugenZhao @tabVersion please let me know if there are any more functions need to wrap.
> feat(rdkafka): unblock fetching functions

- madsim-tonic/src/client.rs
The client uses `Grpc::client_streaming` to send a stream to the server. However, in the current implementation, if the server closes the stream prematurely, the madsim channel will be closed and will return a "connection reset" error to the client. Thus, the client will never receive the response from the server. We should allow the server to close the stream before sending back the response.
> fix(tonic): allows the server to prematurely close the stream in client side streaming

- CHANGELOG.md
- madsim-tonic/Cargo.toml
- madsim-tonic/src/sim.rs
- madsim-tonic/src/transport/server.rs
Some interfaces were included in `madsim-tonic` v0.4.1, but I didn't find it anywhere in GitHub. I suppose there were some local changes made and directly published to crates.io. 🤡 As a result, these interfaces were regressed in `madsim-tonic` v0.4.2 and v0.5.0.
This is a new interface introduced in `tonic` v0.12.
> fix(tonic): add missing interfaces

- madsim-tokio/Cargo.toml
- madsim-tokio/src/sim/runtime.rs
Currently it's required by `sqlx` in various places, for example: https://github.com/madsim-rs/sqlx/blob/0c5c493f31f8848b3a487c6ca15ea0f9d9425462/sqlx-core/src/rt/rt_tokio/mod.rs#L4.
I have bumped the madsim tokio version as well.
> fix(madsim-tokio): add `try_current`

- madsim-tokio/Cargo.toml
- madsim-tokio/src/sim/runtime.rs
- madsim-tonic-build/src/prost.rs
Instead of just returning the mock handle, since we are reusing madsim handle, we check that one exists first in the madsim runtime context.
> fix(madsim-tokio): `try_current` should check the underlying context, to see if there's any running

- madsim-tonic-build/src/prost.rs
- madsim/src/sim/task/mod.rs
Signed-off-by: Bugen Zhao <i@bugenzhao.com>
> fix(madsim): drop the future within the scope of `TaskEnterGuard` when a task is aborted

- madsim-tonic-build/Cargo.toml
- madsim-tonic-build/src/prost.rs
In `tonic-build` version 0.12.3, the `compile` functions has been renamed to `compile_protos`, with the original version now marked as deprecated. For simplicity, we may use a version requirement of `0.12.3` and directly remove the deprecated methods.
As a result, the interfaces are not strictly compatible with the upstream. But as long as the application wants to clean up those warnings about deprecation, we'll be compatible.
> chore(tonic): bump `tonic-build` to 0.12.3

- madsim-etcd-client/src/bytes.rs
- madsim-etcd-client/src/lease.rs
- madsim-rdkafka/CHANGELOG.md
- madsim-rdkafka/Cargo.toml
- madsim-rdkafka/src/sim/admin.rs
- madsim-rdkafka/src/sim/message.rs
- madsim-rdkafka/src/std/admin.rs
- madsim/src/sim/rand.rs
- madsim/src/sim/task/mod.rs
- madsim/src/sim/time/system_time.rs
- tonic-example/Cargo.toml
needed by https://github.com/risingwavelabs/risingwave/pull/20065
Signed-off-by: xxchan <xxchan22f@gmail.com>
> Add `delete_groups` API to `AdminClient`. (no-op in simulation)

- .github/workflows/ci.yml
- Cargo.toml
- madsim-macros/src/lib.rs
- madsim-tonic-build/src/prost.rs
- madsim/src/sim/rand.rs
- madsim/src/sim/runtime/builder.rs
- madsim/src/sim/task/join.rs
Closes #236.
The current ignored test case https://github.com/madsim-rs/madsim/blob/aaa9f9a9690be703a7fc4fcdc6f7a1f2bf5cb9ad/madsim/src/sim/rand.rs#L288-L306
can pass in macOS after this fix.
I also fixed some Clippy errors, while ignoring a few in CI.
> fix(rand): stub `CCRandomGenerateBytes` syscall used in `macos`
